declare namespace NodeJS {
	interface ProcessEnv {
		TACOTRANSLATE_ORIGIN: string;
		TACOTRANSLATE_API_KEY: string;
		TACOTRANSLATE_DEFAULT_LOCALE: string;
		TACOTRANSLATE_PROJECT_LOCALE: string;
		TACOTRANSLATE_PROJECT_LOCALES: string;
	}
}
